### ISSUE TITLE
Send New Tip field at the top of the superhero.com feed does not work

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-ui#854]
When I clicked Send New Tip at the top of the superhero.com feed I was redirected to the web wallet: https://wallet.superhero.com/ while I’m using extension.

My second attempt was also unsuccessful. I filled in all the fields manually, clicked on the Tip icon and got this error:
![Знімок екрана 2020-10-15 о 6 06 23 пп](https://user-images.githubusercontent.com/69896204/96164569-0f029980-0f24-11eb-988b-0c499e01d675.png)

![Знімок екрана 2020-10-15 о 6 44 46 пп](https://user-images.githubusercontent.com/69896204/96165285-14acaf00-0f25-11eb-8cd8-14b2147d8bed.png)
![Знімок екрана 2020-10-15 о 6 45 11 пп](https://user-images.githubusercontent.com/69896204/96165291-17a79f80-0f25-11eb-91ee-df14a90a5522.png)
![Знімок екрана 2020-10-15 о 6 44 00 пп](https://user-images.githubusercontent.com/69896204/96165319-22623480-0f25-11eb-93ad-01e981087f5c.png)

I used: superhero.com ver 0.2.0
wallet ver: 5d91965 / v.0.3.3
Chrome browser, 
Mac OS: 10.15.7

**Comment by mradkov** [comment]
resolved by #849

**Comment by Liubov-crypto** [comment]
This issue is still reproducible on my side:
![Знімок екрана 2020-10-16 о 11 07 51 дп](https://user-images.githubusercontent.com/69896204/96230927-41ea7300-0fa0-11eb-8e00-751dc77c8fc7.png)
![Знімок екрана 2020-10-16 о 11 08 33 дп](https://user-images.githubusercontent.com/69896204/96231011-47e05400-0fa0-11eb-9ed5-7ee059101f89.png)
![Знімок екрана 2020-10-16 о 11 08 58 дп](https://user-images.githubusercontent.com/69896204/96231065-4b73db00-0fa0-11eb-96f3-d870cdd2c1dd.png)
![Знімок екрана 2020-10-16 о 11 09 07 дп](https://user-images.githubusercontent.com/69896204/96231115-4e6ecb80-0fa0-11eb-86fc-cc29b9a2d6ac.png)
![Знімок екрана 2020-10-16 о 11 09 20 дп](https://user-images.githubusercontent.com/69896204/96231157-5169bc00-0fa0-11eb-80c1-a9b562699057.png)
![Знімок екрана 2020-10-16 о 11 09 38 дп](https://user-images.githubusercontent.com/69896204/96231198-5464ac80-0fa0-11eb-96ba-2c968acf0ea6.png)

**Comment by davidyuk** [comment]
should be fixed by #857

**Comment by CedrikNikita** [comment]
Current version of ui doesn't have such problem. Feel free to reopen this issue, if it will pop up in future.
